language: java
jdk:
        - openjdk7

before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
script:
        - ./gradlew check
        - ./gradlew seleniumXvfb
deploy:
        provider: heroku
        api_key:
                secure: 00766a0f-7b19-4a7a-9f7e-ce4b5bf2a328
        app:
                master: tic-taco
                development: tic-taco-staging
