language: java
jdk:
        - openjdk7
script:
        - ./gradlew check
deploy:
        provider: heroku
        api_key:
                secure: 00766a0f-7b19-4a7a-9f7e-ce4b5bf2a328
        app:
                master: tic-taco
