package main.java;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anton' at '10/31/14 6:53 PM' with Gradle 2.1
 *
 * @author anton, @date 10/31/14 6:53 PM
 */
public class Library {
    public boolean SomeLibraryMethod() {
        return true;
    }
}
